### ------------------- Building---------------------------------------

### Create
POST http://localhost:3000/api/v1/buildings/create
Content-Type: application/json

{
    "code": "PC",
    "name": "Pavillon principal",
    "address": "7000, rue Marie-Victorin",
    "yearBuilt": 2005
}

### Get all
Get http://localhost:3000/api/v1/buildings

### Search by id
Get http://localhost:3000/api/v1/buildings/1

### ------------------- Room ---------------------------------------

### Creer new room
POST http://localhost:3000/api/v1/rooms
Content-Type: application/json

{
    "code": "TT",
    "buildingId": "TT",
    "floor": 2
    //"type": "TT",
    //"capacity": 2
}

### Get all room
Get http://localhost:3000/api/v1/rooms

### Get by id
GET http://localhost:3000/api/v1/rooms/7d726df3-fa13-49c2-8f1d-134414ae2e7d

### Update
PATCH http://localhost:3000/api/v1/rooms/8c6a9cd2-377f-4edd-86fa-fbb6a886d70d
Content-Type: application/json

{
    "code": "YY"
}

### Delete room by id
DELETE http://localhost:3000/api/v1/rooms/3c322d12-ebcc-4a28-84a4-d8c3f2189805

### ------------------- Health---------------------------------------

### Health check
Get http://localhost:3000/api/v1/health